provider_config:
    kvm:
        image: CentOS-7-x86_64-GenericCloud-1802.qcow2.xz
        image_url: https://cloud.centos.org/centos/7/images/
        ssh_pwd: Centos123
        ssh_user: root
        ssh_public_key: ~/.ssh/id_rsa.pub
        ssh_private_key: ~/.ssh/id_rsa
        vcpu: 2
        vram: 8192
        vdisk: 60G
        subnet_prefix: 150.132.87.0
        subnet_netmask: 255.255.255.0
        gateway: 150.132.87.1
        nameserver: 150.132.93.100
        ntpserver: SESSIWEGAD00007.ericsson.se 
        domainsuffix: local
instances:
    contrail-controller-01:
        provider: kvm
        host: 150.132.87.104
        bridge: br0
        ip: 150.132.87.243
        additional_interfaces:
            - bridge: br1
              ip: 10.0.0.3
              mask: 255.255.255.0
        roles:
            openstack:
            config_database:
            config:
            control:
            analytics_database:
            analytics:
            analytics_alarm:
            analytics_query-engine:
            analytics_snmp:
            analytics_topology:
            analytics_cassandra:
            analytics_kafka:
            webui:
    contrail-compute-01:
        provider: kvm
        host: 150.132.87.104
        bridge: br0
        ip: 150.132.87.244
        additional_interfaces:
            - bridge: br1
              ip: 10.0.0.4
              mask: 255.255.255.0
        roles:
            openstack_compute:
            vrouter:
    contrail-compute-02:
        provider: kvm
        host: 150.132.87.104
        bridge: br0
        ip: 150.132.87.245
        additional_interfaces:
            - bridge: br1
              ip: 10.0.0.5
              mask: 255.255.255.0
        roles:
            openstack_compute:
            vrouter:

                # Global configuration
global_configuration:
    CONTAINER_REGISTRY: opencontrailnightly

    # Contrail-specific config
contrail_configuration:
    # We separate from API/MGMT and CTRL/DATA networks
    #
    # API/MGMT IP. One controller, so it's the one specified
    # by instance name `contrail-controller-01'
    CONTROLLER_NODES: 150.132.87.243
    # CTRL/DATA. The internal network, only for data traffic
    # of workload and for control traffic between compute nodes
    # and control services
    #
    # Use this to specify the IP addresses on each contrail node where
    # Contrail services are to be hosted. In this instance, all contrail
    # services will run on the CTRL/DATA subnet 10.0.0.0/24
    CONTROL_NODES: 10.0.0.3

    # Important to specify as well the gateway the vRouter will
    # have on the CTRL/DATA network:
    VROUTER_GATEWAY: 10.0.0.1

    # Openstack related
    CLOUD_ORCHESTRATOR: openstack
    OPENSTACK_VERSION: queens
    AUTH_MODE: keystone
    KEYSTONE_AUTH_URL_VERSION: /v3

    # Miscellaneous
    CONTRAIL_VERSION: latest 
    UPGRADE_KERNEL: true

kolla_config:
    kolla_globals:
        network_interface: eth1
        # kolla_external_vip_address: 10.0.0.10
        kolla_internal_vip_address: 150.132.87.246
        enable_ironic: no
        enable_swift: no
        enable_haproxy: yes

