provider_config:
  kvm:
    image: CentOS-7-x86_64-GenericCloud-1802.qcow2.xz
    image_url: https://cloud.centos.org/centos/7/images/
    ssh_pwd: Centos123
    ssh_user: root
    ssh_public_key: ~/.ssh/id_rsa.pub
    ssh_private_key: ~/.ssh/id_rsa
    vcpu: 2
    vram: 8192
    vdisk: 40G
    subnet_prefix: 150.132.87.0
    subnet_netmask: 255.255.255.0
    gateway: 150.132.87.1
    nameserver: 150.132.93.100
    ntpserver: ntp.ubuntu.com 
    domainsuffix: local
instances:
  contrail-controller-01:
    provider: kvm
    host: 150.132.87.104
    bridge: br0
    ip: 150.132.87.243
    roles:
      openstack:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
  contrail-compute-01:
    provider: kvm
    host: 150.132.87.104
    bridge: br0
    ip: 150.132.87.244
    roles:
      openstack_compute:
      vrouter:
  contrail-compute-02:
    provider: kvm
    host: 150.132.87.104
    bridge: br0
    ip: 150.132.87.245
    roles:
      openstack_compute:
      vrouter:
contrail_configuration:
  CLOUD_ORCHESTRATOR: openstack
  OPENSTACK_VERSION: queens
  CONTAINER_REGISTRY: opencontrailnightly
  CONTRAIL_VERSION: latest
  VROUTER_GATEWAY: 150.132.87.1
  UPGRADE_KERNEL: true
  AUTH_MODE: keystone
  KEYSTONE_AUTH_URL_VERSION: /v3

kolla_config:
  kolla_globals:
      #kolla_internal_vip_address: 150.132.87.246
      #kolla_external_vip_address: 150.132.87.247 
    enable_ironic: no
    enable_swift: no
    enable_haproxy: no

